name: CD to Staging

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        run: |
          docker build -t dineshjothiram/myapp:latest .
          docker push dineshjothiram/myapp:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy to Staging
        run: |
          kubectl apply -f k8s/configmap.yaml -n staging
          kubectl apply -f k8s/secret.yaml -n staging
          kubectl apply -f k8s/deployment.yaml -n staging
          kubectl apply -f k8s/service.yaml -n staging
          kubectl apply -f k8s/ingress.yaml -n staging
          kubectl rollout status deployment/myapp -n staging
