name: CI Pipeline

on:
  pull_request:
    branches: [ "main", "develop" ]
  push:
    branches: [ "feature/*" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run Tests
        run: pytest -q app/tests

      - name: Build Docker Image (optional)
        run: docker build -t dineshjothiram/myapp:latest .
